# There is nothing to compile here, but for consistency, let's have a Makefile that does
#  nothing with the expected targets.

.DEFAULT_GOAL:= all

.PHONY: all test clean

all:
	@echo "Nothing to build!"

test:
	@echo "No tests to run!"

clean:
	@echo "Nothing to clean!"
